"""made username unique constraint

Revision ID: 4d8bfa25bbbe
Revises: 
Create Date: 2024-02-07 23:18:49.362250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8bfa25bbbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email', type_='unique')
        batch_op.create_unique_constraint('unique_user_email', ['user_id', 'email', 'username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email', type_='unique')
        batch_op.create_unique_constraint('unique_user_email', ['user_id', 'email'])

    # ### end Alembic commands ###
